[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed && php artisan config:cache && php artisan view:cache && caddy run --config /etc/caddy/Caddyfile"
